license="MIT"
modLoader="javafml"
loaderVersion="[36,37)"
issueTrackerURL="https://github.com/ferreusveritas/DynamicTrees/issues"

[[mods]]
modId="dynamictrees"
version="${file.jarVersion}"
displayName="Dynamic Trees"
updateJSONURL="https://github.com/ferreusveritas/DynamicTrees/blob/1.16.5/version_info.json?raw=true"
displayURL="http://minecraft.curseforge.com/projects/dynamictrees"
logoFile="logo.png"
credits="MaxHyper/Supermassimo & Harley O'Connor for the 1.16 Port"
authors="Ferreusveritas"
description='''
Progressively growing trees.. forests that spread'''

[[dependencies.dynamictrees]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.20,37)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamictrees]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
